name: lint
on:
  push:
    branches:
      - dev
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Run tests
        run: go test ./...
      - name: Run tests
        run: go vet ./...
