// Code generated by /var/folders/ky/99mqlqrd2rd46chcz3tqmxkw0000gn/T/go-build184086314/b001/exe/main -type Foo .; DO NOT EDIT.

package testdata

// DeepCopy generates a deep copy of Foo
func (o Foo) DeepCopy() Foo {
	var cp Foo = o
	if o.Map != nil {
		cp.Map = make(map[string]*Bar, len(o.Map))
		for k, v := range o.Map {
			var cp_Map_v *Bar
			if v != nil {
				cp_Map_v = new(Bar)
				*cp_Map_v = *v
				if v.Slice != nil {
					cp_Map_v.Slice = make([]string, len(v.Slice))
					copy(cp_Map_v.Slice, v.Slice)
				}
			}
			cp.Map[k] = cp_Map_v
		}
	}
	if o.ch != nil {
		cp.ch = make(chan float32, cap(o.ch))
	}
	if o.baz.StringPointer != nil {
		cp.baz.StringPointer = new(string)
		*cp.baz.StringPointer = *o.baz.StringPointer
	}
	return cp
}
