// generated by /var/folders/ky/99mqlqrd2rd46chcz3tqmxkw0000gn/T/go-build426649929/b001/exe/deep-copy --type Foo ./testdata !DO NOT EDIT!

package main

// DeepCopy generates a deep copy of Foo
func (o Foo) DeepCopy() Foo {
	var cp Foo
	cp = o
	if o.Map != nil {
		cp.Map = make(map[*string]*Bar, len(o.Map))
		for k, v := range o.Map {
			var cpk *string
			if k != nil {
				cpk = new(string)
				*cpk = *k
			}
			var cpv *Bar
			if v != nil {
				cpv = new(Bar)
				*cpv = *v
				if v.Slice != nil {
					cpv.Slice = make([]string, len(v.Slice))
					copy(cpv.Slice, v.Slice)
				}
			}
			cp.Map[cpk] = cpv
		}
	}
	if o.ch != nil {
		cp.ch = make(chan float32, cap(o.ch))
	}
	if o.baz.StringPointer != nil {
		cp.baz.StringPointer = new(string)
		*cp.baz.StringPointer = *o.baz.StringPointer
	}
	return cp
}
